In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
headway = pd.read_csv('../Data/Headway Data.csv')

In [3]:
headway.dtypes

CALENDAR_ID                    int64
SERVICE_ABBR                   int64
ADHERENCE_ID                   int64
DATE                          object
ROUTE_ABBR                     int64
BLOCK_ABBR                     int64
OPERATOR                       int64
TRIP_ID                        int64
OVERLOAD_ID                    int64
ROUTE_DIRECTION_NAME          object
TIME_POINT_ABBR               object
ROUTE_STOP_SEQUENCE          float64
TRIP_EDGE                      int64
LATITUDE                     float64
LONGITUDE                    float64
SCHEDULED_TIME                object
ACTUAL_ARRIVAL_TIME           object
ACTUAL_DEPARTURE_TIME         object
ADHERENCE                    float64
SCHEDULED_HDWY               float64
ACTUAL_HDWY                  float64
HDWY_DEV                     float64
ADJUSTED_EARLY_COUNT           int64
ADJUSTED_LATE_COUNT            int64
ADJUSTED_ONTIME_COUNT          int64
STOP_CANCELLED                 int64
PREV_SCHED_STOP_CANCELLED    float64
IS_RELIEF                      int64
BLOCK_STOP_ORDER               int64
DWELL_IN_MINS                float64
dtype: object

In [4]:

headway_a = headway[['DATE','ROUTE_ABBR','BLOCK_ABBR','OPERATOR','TRIP_ID','ROUTE_DIRECTION_NAME','SCHEDULED_TIME', 'SCHEDULED_HDWY', 'ACTUAL_HDWY','HDWY_DEV']]

headway_a.head()

,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
0,2021-11-01,7,1704,2088,297750,TO DOWNTOWN,14:10:00,14.0,15.983333,1.983333
1,2021-11-01,7,1704,2088,297750,TO DOWNTOWN,14:20:00,14.0,17.333333,3.333333
2,2021-11-01,7,1704,2088,297750,TO DOWNTOWN,14:39:00,NaN,NaN,NaN
3,2021-11-01,50,1704,2088,297749,TO DOWNTOWN,15:10:00,NaN,NaN,NaN
4,2021-11-01,50,1704,2088,297749,TO DOWNTOWN,15:27:00,NaN,NaN,NaN

In [5]:
# deleted unwanted columns

headway_f = headway[['DATE','ROUTE_ABBR','TIME_POINT_ABBR','OPERATOR','TRIP_ID','ROUTE_DIRECTION_NAME','SCHEDULED_TIME', 'ACTUAL_ARRIVAL_TIME',
                     'ACTUAL_DEPARTURE_TIME', 'SCHEDULED_HDWY', 'ACTUAL_HDWY','HDWY_DEV']]

headway_f.head()

,DATE,ROUTE_ABBR,TIME_POINT_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
0,2021-11-01,7,HBHS,2088,297750,TO DOWNTOWN,14:10:00,13:59:21,14:12:00,14.0,15.983333,1.983333
1,2021-11-01,7,21BK,2088,297750,TO DOWNTOWN,14:20:00,14:23:21,14:23:21,14.0,17.333333,3.333333
2,2021-11-01,7,MCC5_9,2088,297750,TO DOWNTOWN,14:39:00,14:36:46,14:59:11,NaN,NaN,NaN
3,2021-11-01,50,MLKS,2088,297749,TO DOWNTOWN,15:10:00,15:04:31,15:10:17,NaN,NaN,NaN
4,2021-11-01,50,MCC5_11,2088,297749,TO DOWNTOWN,15:27:00,15:16:59,15:16:59,NaN,NaN,NaN

In [6]:
headway_g = headway_f.sort_values('TIME_POINT_ABBR')

In [7]:
# drilled down to just one route, day, and bus stop

headway_h=headway_g[(headway_g['ROUTE_ABBR']==55) & 
        (headway_g['DATE']=='2021-11-01')&
        (headway_g['TIME_POINT_ABBR']=='HHWM')]

headway_h.head(50)

,DATE,ROUTE_ABBR,TIME_POINT_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
3845,2021-11-01,55,HHWM,1202,300538,FROM DOWNTOWN,09:19:00,09:15:14,09:15:14,NaN,NaN,NaN
3846,2021-11-01,55,HHWM,1202,300548,TO DOWNTOWN,09:36:00,09:15:14,09:38:24,10.0,8.583333,-1.416667
3834,2021-11-01,55,HHWM,1202,300547,TO DOWNTOWN,07:34:00,07:16:22,07:35:30,10.0,9.966666,-0.033334
3833,2021-11-01,55,HHWM,1202,300537,FROM DOWNTOWN,07:17:00,07:16:22,07:16:22,NaN,NaN,NaN
3990,2021-11-01,55,HHWM,2217,300591,TO DOWNTOWN,15:53:00,15:43:23,15:54:37,10.0,10.083333,0.083333
3989,2021-11-01,55,HHWM,2217,300584,FROM DOWNTOWN,15:37:00,15:43:23,15:43:23,NaN,NaN,NaN
3978,2021-11-01,55,HHWM,2217,300590,TO DOWNTOWN,13:45:00,13:28:43,13:47:19,10.0,10.683333,0.683333
3977,2021-11-01,55,HHWM,2217,300583,FROM DOWNTOWN,13:30:00,13:28:43,13:28:43,NaN,NaN,NaN
3966,2021-11-01,55,HHWM,2217,300589,TO DOWNTOWN,11:46:00,11:24:42,11:48:28,10.0,8.633333,-1.366667
3965,2021-11-01,55,HHWM,2217,300582,FROM DOWNTOWN,11:29:00,11:24:42,11:24:42,NaN,NaN,NaN
3954,2021-11-01,55,HHWM,2109,300588,TO DOWNTOWN,09:46:00,09:25:21,09:48:09,10.0,9.750000,-0.250000
3953,2021-11-01,55,HHWM,2109,300581,FROM DOWNTOWN,09:29:00,09:25:21,09:25:21,NaN,NaN,NaN
4001,2021-11-01,55,HHWM,1493,300585,FROM DOWNTOWN,17:52:00,17:47:51,18:09:38,NaN,NaN,NaN
4002,2021-11-01,55,HHWM,1743,300604,TO DOWNTOWN,05:54:00,05:49:06,05:55:43,8.0,7.183333,-0.816667
4050,2021-11-01,55,HHWM,1743,300608,TO DOWNTOWN,13:55:00,13:36:18,13:55:06,10.0,7.783333,-2.216667
4049,2021-11-01,55,HHWM,1743,300598,FROM DOWNTOWN,13:41:00,13:36:18,13:36:18,NaN,NaN,NaN
4038,2021-11-01,55,HHWM,1743,300607,TO DOWNTOWN,11:56:00,11:40:18,11:57:02,10.0,8.566666,-1.433334
4037,2021-11-01,55,HHWM,1743,300597,FROM DOWNTOWN,11:39:00,11:40:18,11:40:18,NaN,NaN,NaN
4026,2021-11-01,55,HHWM,1743,300606,TO DOWNTOWN,09:56:00,09:36:20,09:56:52,10.0,8.716666,-1.283334
4025,2021-11-01,55,HHWM,1743,300596,FROM DOWNTOWN,09:39:00,09:36:20,09:36:20,NaN,NaN,NaN
4014,2021-11-01,55,HHWM,1743,300605,TO DOWNTOWN,07:55:00,07:36:07,07:55:59,11.0,9.100000,-1.900000
4013,2021-11-01,55,HHWM,1743,300595,FROM DOWNTOWN,07:39:00,07:36:07,07:36:07,NaN,NaN,NaN
3942,2021-11-01,55,HHWM,2109,300587,TO DOWNTOWN,07:44:00,07:27:09,07:46:53,10.0,11.383333,1.383333
3941,2021-11-01,55,HHWM,2109,300580,FROM DOWNTOWN,07:29:00,07:27:09,07:27:09,NaN,NaN,NaN
3881,2021-11-01,55,HHWM,2221,300541,FROM DOWNTOWN,15:27:00,15:23:03,15:23:03,NaN,NaN,NaN
3870,2021-11-01,55,HHWM,1202,300550,TO DOWNTOWN,13:35:00,13:18:46,13:36:38,9.0,9.083333,0.083333
3869,2021-11-01,55,HHWM,1202,300540,FROM DOWNTOWN,13:20:00,13:18:46,13:18:46,NaN,NaN,NaN
3858,2021-11-01,55,HHWM,1202,300549,TO DOWNTOWN,11:36:00,11:15:42,11:39:50,10.0,12.650000,2.650000
3857,2021-11-01,55,HHWM,1202,300539,FROM DOWNTOWN,11:19:00,11:15:42,11:15:42,NaN,NaN,NaN
3882,2021-11-01,55,HHWM,2221,300551,TO DOWNTOWN,15:43:00,15:23:03,15:44:32,10.0,10.033333,0.033333
3930,2021-11-01,55,HHWM,2109,300586,TO DOWNTOWN,05:46:00,05:36:22,05:48:32,8.0,9.483333,1.483333
3929,2021-11-01,55,HHWM,2221,300536,FROM DOWNTOWN,23:38:00,23:34:58,23:36:52,NaN,NaN,NaN
3918,2021-11-01,55,HHWM,2221,300545,TO DOWNTOWN,21:58:00,21:36:17,22:00:06,20.0,20.566666,0.566666
3917,2021-11-01,55,HHWM,2221,300534,FROM DOWNTOWN,21:38:00,21:36:17,21:36:17,NaN,NaN,NaN
3906,2021-11-01,55,HHWM,2221,300544,TO DOWNTOWN,19:59:00,19:44:43,20:01:38,20.0,21.150000,1.150000
3905,2021-11-01,55,HHWM,2221,300535,FROM DOWNTOWN,19:44:00,19:44:43,19:44:43,NaN,NaN,NaN
3894,2021-11-01,55,HHWM,2221,300543,TO DOWNTOWN,18:02:00,17:40:07,18:04:18,15.0,15.800000,0.800000
3893,2021-11-01,55,HHWM,2221,300542,FROM DOWNTOWN,17:42:00,17:40:07,17:40:07,NaN,NaN,NaN
3762,2021-11-01,55,HHWM,1158,300502,TO DOWNTOWN,13:26:00,13:05:36,13:27:33,10.0,10.250000,0.250000
3761,2021-11-01,55,HHWM,1158,300492,FROM DOWNTOWN,13:10:00,13:05:36,13:05:36,NaN,NaN,NaN
3750,2021-11-01,55,HHWM,1158,300501,TO DOWNTOWN,11:26:00,11:09:10,11:27:11,10.0,9.983333,-0.016667
3749,2021-11-01,55,HHWM,1158,300491,FROM DOWNTOWN,11:09:00,11:09:10,11:09:10,NaN,NaN,NaN
3773,2021-11-01,55,HHWM,907,300493,FROM DOWNTOWN,15:17:00,15:12:57,15:12:57,NaN,NaN,NaN
3798,2021-11-01,55,HHWM,907,300496,TO DOWNTOWN,19:39:00,19:29:01,19:40:29,20.0,19.566666,-0.433334
3797,2021-11-01,55,HHWM,907,300487,FROM DOWNTOWN,19:29:00,19:29:01,19:29:01,NaN,NaN,NaN
3786,2021-11-01,55,HHWM,907,300495,TO DOWNTOWN,17:47:00,17:30:09,17:48:30,15.0,14.250000,-0.750000
3785,2021-11-01,55,HHWM,907,300494,FROM DOWNTOWN,17:32:00,17:30:09,17:30:09,NaN,NaN,NaN
3774,2021-11-01,55,HHWM,907,300503,TO DOWNTOWN,15:33:00,15:12:57,15:34:30,10.0,9.750000,-0.250000
3738,2021-11-01,55,HHWM,1158,300500,TO DOWNTOWN,09:26:00,09:11:12,09:29:49,10.0,12.600000,2.600000
3690,2021-11-01,55,HHWM,1228,300446,TO DOWNTOWN,13:16:00,12:56:48,13:17:18,10.0,8.500000,-1.500000

In [8]:
# ordered by scheduled time

headway_i = headway_h.sort_values(by='SCHEDULED_TIME', ascending=True)
headway_i.head(50)

# df.sort_values(by='DateTime1',ascending=True)

,DATE,ROUTE_ABBR,TIME_POINT_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV
3320,2021-11-01,55,HHWM,1716,300293,TO DOWNTOWN,04:22:00,04:14:12,04:22:48,NaN,NaN,NaN
3408,2021-11-01,55,HHWM,557,300347,TO DOWNTOWN,04:47:00,04:39:44,04:47:37,25.0,24.816666,-0.183334
3519,2021-11-01,55,HHWM,329,300398,TO DOWNTOWN,05:07:00,05:00:06,05:07:37,20.0,20.000000,0.000000
3642,2021-11-01,55,HHWM,1228,300442,TO DOWNTOWN,05:19:00,05:13:07,05:22:12,12.0,14.583333,2.583333
3714,2021-11-01,55,HHWM,1158,300498,TO DOWNTOWN,05:28:00,05:19:17,05:29:32,9.0,7.333333,-1.666667
3822,2021-11-01,55,HHWM,1202,300546,TO DOWNTOWN,05:38:00,05:33:58,05:39:03,10.0,9.516666,-0.483334
3930,2021-11-01,55,HHWM,2109,300586,TO DOWNTOWN,05:46:00,05:36:22,05:48:32,8.0,9.483333,1.483333
4002,2021-11-01,55,HHWM,1743,300604,TO DOWNTOWN,05:54:00,05:49:06,05:55:43,8.0,7.183333,-0.816667
3331,2021-11-01,55,HHWM,1716,300286,FROM DOWNTOWN,05:57:00,05:52:45,05:52:45,NaN,NaN,NaN
3332,2021-11-01,55,HHWM,1716,300294,TO DOWNTOWN,06:04:00,05:53:07,06:04:49,10.0,9.100000,-0.900000
4110,2021-11-01,55,HHWM,2055,300616,TO DOWNTOWN,06:13:00,06:00:26,06:14:45,9.0,9.933333,0.933333
3419,2021-11-01,55,HHWM,557,300338,FROM DOWNTOWN,06:22:00,06:17:49,06:17:49,NaN,NaN,NaN
4182,2021-11-01,55,HHWM,2035,300632,TO DOWNTOWN,06:23:00,06:21:06,06:23:15,10.0,8.500000,-1.500000
3420,2021-11-01,55,HHWM,557,300350,TO DOWNTOWN,06:33:00,06:18:08,06:32:22,10.0,9.116666,-0.883334
3530,2021-11-01,55,HHWM,329,300388,FROM DOWNTOWN,06:42:00,06:39:44,06:39:44,NaN,NaN,NaN
4278,2021-11-01,55,HHWM,1194,300644,TO DOWNTOWN,06:43:00,06:44:04,06:44:04,10.0,11.700000,1.700000
3531,2021-11-01,55,HHWM,329,300402,TO DOWNTOWN,06:53:00,06:39:44,06:53:49,10.0,9.750000,-0.250000
3653,2021-11-01,55,HHWM,1228,300436,FROM DOWNTOWN,06:57:00,06:54:16,06:54:16,NaN,NaN,NaN
4350,2021-11-01,55,HHWM,2098,300657,TO DOWNTOWN,07:03:00,07:09:36,07:11:18,10.0,17.483333,7.483333
3725,2021-11-01,55,HHWM,1158,300489,FROM DOWNTOWN,07:07:00,07:03:11,07:03:11,NaN,NaN,NaN
3654,2021-11-01,55,HHWM,1228,300443,TO DOWNTOWN,07:14:00,06:54:16,07:16:19,11.0,5.016666,-5.983334
3833,2021-11-01,55,HHWM,1202,300537,FROM DOWNTOWN,07:17:00,07:16:22,07:16:22,NaN,NaN,NaN
3726,2021-11-01,55,HHWM,1158,300499,TO DOWNTOWN,07:24:00,07:03:11,07:25:32,10.0,9.216666,-0.783334
3941,2021-11-01,55,HHWM,2109,300580,FROM DOWNTOWN,07:29:00,07:27:09,07:27:09,NaN,NaN,NaN
3834,2021-11-01,55,HHWM,1202,300547,TO DOWNTOWN,07:34:00,07:16:22,07:35:30,10.0,9.966666,-0.033334
4013,2021-11-01,55,HHWM,1743,300595,FROM DOWNTOWN,07:39:00,07:36:07,07:36:07,NaN,NaN,NaN
3942,2021-11-01,55,HHWM,2109,300587,TO DOWNTOWN,07:44:00,07:27:09,07:46:53,10.0,11.383333,1.383333
3343,2021-11-01,55,HHWM,1716,300287,FROM DOWNTOWN,07:49:00,07:47:26,07:47:26,NaN,NaN,NaN
4014,2021-11-01,55,HHWM,1743,300605,TO DOWNTOWN,07:55:00,07:36:07,07:55:59,11.0,9.100000,-1.900000
4121,2021-11-01,55,HHWM,2055,300610,FROM DOWNTOWN,07:59:00,07:58:46,07:58:46,NaN,NaN,NaN
3344,2021-11-01,55,HHWM,1716,300295,TO DOWNTOWN,08:06:00,07:47:42,08:07:27,11.0,11.466666,0.466666
4193,2021-11-01,55,HHWM,2035,300624,FROM DOWNTOWN,08:09:00,08:09:46,08:09:46,NaN,NaN,NaN
4122,2021-11-01,55,HHWM,2055,300617,TO DOWNTOWN,08:16:00,08:04:39,08:17:40,10.0,10.216666,0.216666
3431,2021-11-01,55,HHWM,557,300341,FROM DOWNTOWN,08:19:00,08:24:02,08:24:02,NaN,NaN,NaN
4194,2021-11-01,55,HHWM,2035,300633,TO DOWNTOWN,08:26:00,08:09:46,08:24:51,10.0,7.183333,-2.816667
4289,2021-11-01,55,HHWM,1194,300638,FROM DOWNTOWN,08:29:00,08:33:15,08:33:15,NaN,NaN,NaN
3432,2021-11-01,55,HHWM,557,300351,TO DOWNTOWN,08:36:00,08:24:23,08:35:07,10.0,10.266666,0.266666
3542,2021-11-01,55,HHWM,329,300392,FROM DOWNTOWN,08:39:00,08:43:59,08:43:59,NaN,NaN,NaN
4290,2021-11-01,55,HHWM,1194,300645,TO DOWNTOWN,08:46:00,08:33:34,08:48:18,10.0,13.183333,3.183333
4427,2021-11-01,55,HHWM,1419,300651,FROM DOWNTOWN,08:49:00,08:57:04,08:57:04,NaN,NaN,NaN
4361,2021-11-01,55,HHWM,2098,300651,FROM DOWNTOWN,08:49:00,08:46:02,08:46:02,NaN,NaN,NaN
3543,2021-11-01,55,HHWM,329,300403,TO DOWNTOWN,08:56:00,08:43:59,08:58:14,10.0,9.933333,-0.066667
3665,2021-11-01,55,HHWM,1228,300437,FROM DOWNTOWN,08:59:00,08:57:07,08:57:07,NaN,NaN,NaN
4362,2021-11-01,55,HHWM,2098,300658,TO DOWNTOWN,09:06:00,08:46:02,09:09:38,10.0,11.400000,1.400000
3737,2021-11-01,55,HHWM,1158,300490,FROM DOWNTOWN,09:09:00,09:11:12,09:11:12,NaN,NaN,NaN
3666,2021-11-01,55,HHWM,1228,300444,TO DOWNTOWN,09:16:00,08:57:07,09:17:13,10.0,7.583333,-2.416667
3845,2021-11-01,55,HHWM,1202,300538,FROM DOWNTOWN,09:19:00,09:15:14,09:15:14,NaN,NaN,NaN
3738,2021-11-01,55,HHWM,1158,300500,TO DOWNTOWN,09:26:00,09:11:12,09:29:49,10.0,12.600000,2.600000
3953,2021-11-01,55,HHWM,2109,300581,FROM DOWNTOWN,09:29:00,09:25:21,09:25:21,NaN,NaN,NaN
3846,2021-11-01,55,HHWM,1202,300548,TO DOWNTOWN,09:36:00,09:15:14,09:38:24,10.0,8.583333,-1.416667

In [9]:

headway_i['DEV_PERCENT'] = headway_i.HDWY_DEV/headway_i.SCHEDULED_HDWY * 100
headway_i

,DATE,ROUTE_ABBR,TIME_POINT_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,DEV_PERCENT
3320,2021-11-01,55,HHWM,1716,300293,TO DOWNTOWN,04:22:00,04:14:12,04:22:48,NaN,NaN,NaN,NaN
3408,2021-11-01,55,HHWM,557,300347,TO DOWNTOWN,04:47:00,04:39:44,04:47:37,25.0,24.816666,-0.183334,-0.733336
3519,2021-11-01,55,HHWM,329,300398,TO DOWNTOWN,05:07:00,05:00:06,05:07:37,20.0,20.000000,0.000000,0.000000
3642,2021-11-01,55,HHWM,1228,300442,TO DOWNTOWN,05:19:00,05:13:07,05:22:12,12.0,14.583333,2.583333,21.527775
3714,2021-11-01,55,HHWM,1158,300498,TO DOWNTOWN,05:28:00,05:19:17,05:29:32,9.0,7.333333,-1.666667,-18.518522
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3821,2021-11-01,55,HHWM,907,300488,FROM DOWNTOWN,23:18:00,23:13:08,23:17:33,NaN,NaN,NaN,NaN
3627,2021-11-01,55,HHWM,1815,300407,TO DOWNTOWN,23:18:00,22:56:19,23:19:46,60.0,60.166666,0.166666,0.277777
3929,2021-11-01,55,HHWM,2221,300536,FROM DOWNTOWN,23:38:00,23:34:58,23:36:52,NaN,NaN,NaN,NaN
4109,2021-11-01,55,HHWM,1814,300594,FROM DOWNTOWN,23:58:00,23:54:36,23:59:09,NaN,NaN,NaN,NaN
3638,2021-11-01,55,HHWM,1815,300397,FROM DOWNTOWN,24:58:00,24:58:26,25:00:14,NaN,NaN,NaN,NaN

In [10]:
# bunched if actually headway is 50% of the scheduled headway. So if the scheduled headway is 10 minutes, then it's bunched if the busses are less than 5 minutes apart. 

# gapped if scheudled headway is 10 minutes and the busses are more than 15 minutes apart if scheduled headway is 10 minutes and the actual headway is 15 minutes 

# created column showing bunching vs gapping
# more than 50% = gapping
# less than -50% = bunching

headway_i['BUNCH/GAP']=''

headway_i.loc[headway_i['DEV_PERCENT'] >50, 'BUNCH/GAP']= 'gap'
headway_i.loc[headway_i['DEV_PERCENT'] <-50, 'BUNCH/GAP']= 'bunch'

headway_i.head(50)

,DATE,ROUTE_ABBR,TIME_POINT_ABBR,OPERATOR,TRIP_ID,ROUTE_DIRECTION_NAME,SCHEDULED_TIME,ACTUAL_ARRIVAL_TIME,ACTUAL_DEPARTURE_TIME,SCHEDULED_HDWY,ACTUAL_HDWY,HDWY_DEV,DEV_PERCENT,BUNCH/GAP
3320,2021-11-01,55,HHWM,1716,300293,TO DOWNTOWN,04:22:00,04:14:12,04:22:48,NaN,NaN,NaN,NaN,
3408,2021-11-01,55,HHWM,557,300347,TO DOWNTOWN,04:47:00,04:39:44,04:47:37,25.0,24.816666,-0.183334,-0.733336,
3519,2021-11-01,55,HHWM,329,300398,TO DOWNTOWN,05:07:00,05:00:06,05:07:37,20.0,20.000000,0.000000,0.000000,
3642,2021-11-01,55,HHWM,1228,300442,TO DOWNTOWN,05:19:00,05:13:07,05:22:12,12.0,14.583333,2.583333,21.527775,
3714,2021-11-01,55,HHWM,1158,300498,TO DOWNTOWN,05:28:00,05:19:17,05:29:32,9.0,7.333333,-1.666667,-18.518522,
3822,2021-11-01,55,HHWM,1202,300546,TO DOWNTOWN,05:38:00,05:33:58,05:39:03,10.0,9.516666,-0.483334,-4.833340,
3930,2021-11-01,55,HHWM,2109,300586,TO DOWNTOWN,05:46:00,05:36:22,05:48:32,8.0,9.483333,1.483333,18.541663,
4002,2021-11-01,55,HHWM,1743,300604,TO DOWNTOWN,05:54:00,05:49:06,05:55:43,8.0,7.183333,-0.816667,-10.208338,
3331,2021-11-01,55,HHWM,1716,300286,FROM DOWNTOWN,05:57:00,05:52:45,05:52:45,NaN,NaN,NaN,NaN,
3332,2021-11-01,55,HHWM,1716,300294,TO DOWNTOWN,06:04:00,05:53:07,06:04:49,10.0,9.100000,-0.900000,-9.000000,
4110,2021-11-01,55,HHWM,2055,300616,TO DOWNTOWN,06:13:00,06:00:26,06:14:45,9.0,9.933333,0.933333,10.370367,
3419,2021-11-01,55,HHWM,557,300338,FROM DOWNTOWN,06:22:00,06:17:49,06:17:49,NaN,NaN,NaN,NaN,
4182,2021-11-01,55,HHWM,2035,300632,TO DOWNTOWN,06:23:00,06:21:06,06:23:15,10.0,8.500000,-1.500000,-15.000000,
3420,2021-11-01,55,HHWM,557,300350,TO DOWNTOWN,06:33:00,06:18:08,06:32:22,10.0,9.116666,-0.883334,-8.833340,
3530,2021-11-01,55,HHWM,329,300388,FROM DOWNTOWN,06:42:00,06:39:44,06:39:44,NaN,NaN,NaN,NaN,
4278,2021-11-01,55,HHWM,1194,300644,TO DOWNTOWN,06:43:00,06:44:04,06:44:04,10.0,11.700000,1.700000,17.000000,
3531,2021-11-01,55,HHWM,329,300402,TO DOWNTOWN,06:53:00,06:39:44,06:53:49,10.0,9.750000,-0.250000,-2.500000,
3653,2021-11-01,55,HHWM,1228,300436,FROM DOWNTOWN,06:57:00,06:54:16,06:54:16,NaN,NaN,NaN,NaN,
4350,2021-11-01,55,HHWM,2098,300657,TO DOWNTOWN,07:03:00,07:09:36,07:11:18,10.0,17.483333,7.483333,74.833330,gap
3725,2021-11-01,55,HHWM,1158,300489,FROM DOWNTOWN,07:07:00,07:03:11,07:03:11,NaN,NaN,NaN,NaN,
3654,2021-11-01,55,HHWM,1228,300443,TO DOWNTOWN,07:14:00,06:54:16,07:16:19,11.0,5.016666,-5.983334,-54.393945,bunch
3833,2021-11-01,55,HHWM,1202,300537,FROM DOWNTOWN,07:17:00,07:16:22,07:16:22,NaN,NaN,NaN,NaN,
3726,2021-11-01,55,HHWM,1158,300499,TO DOWNTOWN,07:24:00,07:03:11,07:25:32,10.0,9.216666,-0.783334,-7.833340,
3941,2021-11-01,55,HHWM,2109,300580,FROM DOWNTOWN,07:29:00,07:27:09,07:27:09,NaN,NaN,NaN,NaN,
3834,2021-11-01,55,HHWM,1202,300547,TO DOWNTOWN,07:34:00,07:16:22,07:35:30,10.0,9.966666,-0.033334,-0.333340,
4013,2021-11-01,55,HHWM,1743,300595,FROM DOWNTOWN,07:39:00,07:36:07,07:36:07,NaN,NaN,NaN,NaN,
3942,2021-11-01,55,HHWM,2109,300587,TO DOWNTOWN,07:44:00,07:27:09,07:46:53,10.0,11.383333,1.383333,13.833330,
3343,2021-11-01,55,HHWM,1716,300287,FROM DOWNTOWN,07:49:00,07:47:26,07:47:26,NaN,NaN,NaN,NaN,
4014,2021-11-01,55,HHWM,1743,300605,TO DOWNTOWN,07:55:00,07:36:07,07:55:59,11.0,9.100000,-1.900000,-17.272727,
4121,2021-11-01,55,HHWM,2055,300610,FROM DOWNTOWN,07:59:00,07:58:46,07:58:46,NaN,NaN,NaN,NaN,
3344,2021-11-01,55,HHWM,1716,300295,TO DOWNTOWN,08:06:00,07:47:42,08:07:27,11.0,11.466666,0.466666,4.242418,
4193,2021-11-01,55,HHWM,2035,300624,FROM DOWNTOWN,08:09:00,08:09:46,08:09:46,NaN,NaN,NaN,NaN,
4122,2021-11-01,55,HHWM,2055,300617,TO DOWNTOWN,08:16:00,08:04:39,08:17:40,10.0,10.216666,0.216666,2.166660,
3431,2021-11-01,55,HHWM,557,300341,FROM DOWNTOWN,08:19:00,08:24:02,08:24:02,NaN,NaN,NaN,NaN,
4194,2021-11-01,55,HHWM,2035,300633,TO DOWNTOWN,08:26:00,08:09:46,08:24:51,10.0,7.183333,-2.816667,-28.166670,
4289,2021-11-01,55,HHWM,1194,300638,FROM DOWNTOWN,08:29:00,08:33:15,08:33:15,NaN,NaN,NaN,NaN,
3432,2021-11-01,55,HHWM,557,300351,TO DOWNTOWN,08:36:00,08:24:23,08:35:07,10.0,10.266666,0.266666,2.666660,
3542,2021-11-01,55,HHWM,329,300392,FROM DOWNTOWN,08:39:00,08:43:59,08:43:59,NaN,NaN,NaN,NaN,
4290,2021-11-01,55,HHWM,1194,300645,TO DOWNTOWN,08:46:00,08:33:34,08:48:18,10.0,13.183333,3.183333,31.833330,
4427,2021-11-01,55,HHWM,1419,300651,FROM DOWNTOWN,08:49:00,08:57:04,08:57:04,NaN,NaN,NaN,NaN,
4361,2021-11-01,55,HHWM,2098,300651,FROM DOWNTOWN,08:49:00,08:46:02,08:46:02,NaN,NaN,NaN,NaN,
3543,2021-11-01,55,HHWM,329,300403,TO DOWNTOWN,08:56:00,08:43:59,08:58:14,10.0,9.933333,-0.066667,-0.666670,
3665,2021-11-01,55,HHWM,1228,300437,FROM DOWNTOWN,08:59:00,08:57:07,08:57:07,NaN,NaN,NaN,NaN,
4362,2021-11-01,55,HHWM,2098,300658,TO DOWNTOWN,09:06:00,08:46:02,09:09:38,10.0,11.400000,1.400000,14.000000,
3737,2021-11-01,55,HHWM,1158,300490,FROM DOWNTOWN,09:09:00,09:11:12,09:11:12,NaN,NaN,NaN,NaN,
3666,2021-11-01,55,HHWM,1228,300444,TO DOWNTOWN,09:16:00,08:57:07,09:17:13,10.0,7.583333,-2.416667,-24.166670,
3845,2021-11-01,55,HHWM,1202,300538,FROM DOWNTOWN,09:19:00,09:15:14,09:15:14,NaN,NaN,NaN,NaN,
3738,2021-11-01,55,HHWM,1158,300500,TO DOWNTOWN,09:26:00,09:11:12,09:29:49,10.0,12.600000,2.600000,26.000000,
3953,2021-11-01,55,HHWM,2109,300581,FROM DOWNTOWN,09:29:00,09:25:21,09:25:21,NaN,NaN,NaN,NaN,
3846,2021-11-01,55,HHWM,1202,300548,TO DOWNTOWN,09:36:00,09:15:14,09:38:24,10.0,8.583333,-1.416667,-14.166670,

In [11]:
# now will try on entire data frame to find trends